#!/usr/bin/env bash
# The script to install inginx
#The condition :  Nginx should be listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo service nginx restart

