#!/usr/bin/env bash
# find out what keeping your Ubuntu installation from listening on port
# debugging nginx (service (init) must say that nginx is not running)
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart

