#!/usr/bin/env bash
# The script is to restart apache 2 and returning a page
# with  Hello Holberton in it when querying the root of it.
# Start the Apache service
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart

